### ISSUE TITLE
Specify rules on how to contribute 

### ISSUE THREAD

**Issue by jinpark** [CodeforeveryoneSeoul/codeforeveryone#15]
I personally like https://guides.github.com/introduction/flow/ way. Only thing I would like to change here is that branches get merged to master before deployment.

This would mean, no commits directly to master without a PR. All code is reviewed. We can also integrate a continuous integration step if we do things this way.

I'll update the readme to specify this after I get @hassanabidpk 's approval

@hassanabidpk do you have any comments

**Comment by hassanabidpk** [comment]
@jinpark  lets do it.. I am not used Github regarding techniques.. But it is MUST!

**Comment by hassanabidpk** [comment]
I think you already added in readme.

**Comment by jinpark** [comment]
Yea, I forgot  I did this already :P
