### ISSUE TITLE
Use template inheritance to create a base template

### ISSUE THREAD

**Issue by jinpark** [CodeforeveryoneSeoul/codeforeveryone#16]
We have too much duplicated html. We should be using a base template that includes the header and footer and just override the content

**Comment by jinpark** [comment]
I'll take this but I would like @RachellCalhoun to take a look at my code when I make the PR

**Comment by RachellCalhoun** [comment]
Ok, I'll check it out when you're done.

**Comment by jinpark** [comment]
@RachellCalhoun feel free to take it on yourself if you want to give it a shot!

**Comment by jinpark** [comment]
This is done!
