### ISSUE TITLE
Turn on https/ssl for website

### ISSUE THREAD

**Issue by hassanabidpk** [CodeforeveryoneSeoul/codeforeveryone#19]
I will take this one because we have got it from name-cheap

**Comment by jinpark** [comment]
Thanks @hassanabidpk ssl cert stuff is so annoying

**Comment by hassanabidpk** [comment]
Ha-ha. Yes. I finished quickly this time. Sent email to python anywhere to do final step. Let's hope for the best. First time.it took me 7 days (earlier this year) on naver server. Haha

**Comment by hassanabidpk** [comment]
It was done yesterday !  No code required but next step of this issue is #33

**Comment by jinpark** [comment]
Lets leave this open until we get that PR merged

**Comment by hassanabidpk** [comment]
Fixed
