### ISSUE TITLE
Require email and name for contact us page

### ISSUE THREAD

**Issue by jinpark** [CodeforeveryoneSeoul/codeforeveryone#29]
needs both clientside and server side validation

**Comment by jinpark** [comment]
I just did some really easy html validation but we might want some more fancy validation on the front end. Should be easy to use flash messages for backend validation. Will let @hassanabidpk figure it out :D

https://docs.djangoproject.com/en/1.8/ref/contrib/messages/

**Comment by hassanabidpk** [comment]
This was fixed
