### ISSUE TITLE
Force all links to be https

### ISSUE THREAD

**Issue by hassanabidpk** [CodeforeveryoneSeoul/codeforeveryone#33]
Follow this tutorial : https://www.pythonanywhere.com/wiki/ForcingHTTPS

**Comment by jinpark** [comment]
As we've talked about in slack

That link is for old django versions. We can just do whats specified in https://docs.djangoproject.com/en/1.8/topics/security/#ssl-https for django 1.8

**Comment by hassanabidpk** [comment]
fixed in #19
