### ISSUE TITLE
Clean up the contact us page

### ISSUE THREAD

**Issue by jinpark** [CodeforeveryoneSeoul/codeforeveryone#34]
The form alignment looks all wrong

I can take this since I found it but anyone can do it :)

**Comment by jinpark** [comment]
@RachellCalhoun can you try to fix this too?

http://www.getmdl.io/components/index.html#layout-section at the bottom is the grid section. That will probably be helpful!

**Comment by RachellCalhoun** [comment]
Can we mark this as done? or do you want to tackle the message again?

**Comment by jinpark** [comment]
Yea, this looks good enough imo.
